version: "3.7"
services:
  mosquitto:
    image: mosquitto
    restart: on-failure
    ports:
      - "1883"
    volumes:
      - mosquittoData:/var/lib/mosquitto/
  grafana:
    image: grafana/grafana
    ports:
      - "3000"
    restart: always
    links:
      - influxdb
    volumes:
      - grafanaData:/var/lib/grafana
  indluxdbStateSubscriber:
    image: influxdb-subscriber
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - mosquitto
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    restart: always
    volumes:
      - influxdbData:/var/lib/influxdb
volumes:
  influxdbData:
  grafanaData:
  mosquittoData:
