version: "3.7"
services:
  mosquitto:
    image: mosquitto
    restart: on-failure
    ports:
      - "1883:1883"
    volumes:
      - mosquittoData:/var/lib/mosquitto/
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always
    links:
      - influxdb
    volumes:
      - grafanaData:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - nginx_network
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./certs/selfhydro.ddns.net:/certs/selfhydro.ddns.net
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - 80:80
      - 443:443
    links:
      - grafana
    networks:
      - nginx_network
  indluxdbStateSubscriber:
    image: influxdb-subscriber
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - mosquitto
      - influxdb
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    restart: always
    volumes:
      - influxdbData:/var/lib/influxdb
volumes:
  influxdbData:
  grafanaData:
  mosquittoData:

networks:
  nginx_network:
