---
resources:
- name: SelfHydroDashboard
  type: git
  source:
    uri: https://github.com/selfhydro/SelfHydroDashboard.git

- name: StateInfluxDBSubscriberImage
  type: docker-image
  source:
    email: ((docker-hub.email))
    username: ((docker-hub.username))
    password: ((docker-hub.password))
    repository: ((docker-hub.username))/state-influx-db-subscriber

- name: version
  type: semver
  source:
    driver: gcs
    bucket: selfhydro-versions
    key: SelfHydroDashboard
    json_key: |
      {
        "type": "service_account",
        "project_id": "selfhydro-197504",
        "private_key_id": "((gcs-service_account.private_key_id))",
        "private_key": "((gcs-service_account.private_key))",
        "client_email": "((gcs-service_account.client_email))",
        "client_id": "((gcs-service_account.client_id))",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/concourse-deployment%40selfhydro-197504.iam.gserviceaccount.com"
      }

jobs:
- name: test
  plan:
  - get: SelfHydroDashboard
    trigger: true
  - task: unit-test
    file: SelfHydroDashboard/ci/unit-test.yml

- name: build
  plan:
  - get: version
    params: {bump: patch}
  - get: SelfHydroDashboard
    trigger: true
    passed: [test]
  - put: version
    params: {file: version/version}
  - put: StateInfluxDBSubscriberImage
    params:
      build: SelfHydroDashboard
      labels:
        version: version/version
